---
name: FreeBSD Build

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

env:
  PKG_NAME: mail-alias-resolve-ldap
  PKG_DEPS: "curl go"

jobs:
  build:
    runs-on: macos-12
    name: Build on FreeBSD
    steps:
      - uses: actions/checkout@v2
      - name: Build on FreeBSD
        uses: vmactions/freebsd-vm@v0.2.9
        id: build
        with:
          usesh: true
          prepare: |
            pkg install -y ${{ env.PKG_DEPS }}

          run: |
            go build
            tar -cJvf ${{ env.PKG_NAME }}-freebsd-amd64-latest.tar.xz ${{ env.PKG_NAME }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PKG_NAME }}-freebsd-amd64-latest
          path: ${{ env.PKG_NAME }}-freebsd-amd64-latest.tar.xz
