name: Release artifacts

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - '**'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

    - name: Wait for FreeBSD build
      uses: lewagon/wait-on-check-action@v1.3.1
      with:
        ref: ${{ github.ref }}
        check-name: 'Build on FreeBSD'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 10

    - name: Wait for Linux builds
      uses: lewagon/wait-on-check-action@v1.3.1
      with:
        ref: ${{ github.ref }}
        check-name: 'build'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 10

    - name: Download FreeBSD artifact
      id: download-freebsd-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build-freebsd.yml

    - name: Download Linux artifacts
      id: download-linux-artifacts
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml

    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: "latest"
        files: |
          mail-alias-resolve-ldap-linux-amd64-latest.tar.xz
          mail-alias-resolve-ldap-freebsd-amd64-latest.tar.xz
